KG_DATA_DIR: "/u/project/pasaniuc/pasaniucdata/admixture/1000G_haplotype/1000GP_Phase3"
CHR: 20
POPS:
  - "AFR"
  - "EUR"
  
# Array SNP filtering
DATA_DIR: "data"

# MAF filtering
MAF_THRESHOLD: 0.05
MAF_MODE: "OR"

# HAPGEN setting
HAPGEN_NUM_HAPLOS: 20000
HAPGEN2_PATH: "/u/project/pasaniuc/pasaniucdata/software/hapgen/hapgen2"

# admixture simulation software
ADMIX_SIMU_DIR: "/u/project/pasaniuc/pasaniucdata/admixture/software/admix-simu"
