INPUT_DATA_DIR: "/u/project/pasaniuc/pasaniucdata/admixture/1000G_haplotype/1000GP_Phase3"
CHR: 22 # use the chromosome 22
POPS:
  - "AFR"
  - "EUR"
  
# Array SNP filtering
SNP_LIST: "data/ukb_imputed_blocks.txt"
# ARRAY_SNP_DIR: "/u/project/sgss/UKBB/data/cal"

# MAF filtering
MAF_THRESHOLD: 0.05
MAF_MODE: "OR"

# HAPGEN setting
HAPGEN_NUM_HAPLOS: 20000
HAPGEN2_PATH: "/u/project/pasaniuc/pasaniucdata/software/hapgen/hapgen2"

# admixture simulation software
ADMIX_SIMU_DIR: "/u/project/pasaniuc/pasaniucdata/admixture/software/admix-simu"
