KG_DATA_DIR: "/u/project/pasaniuc/pasaniucdata/admixture/1000G_haplotype/1000GP_Phase3"
CHR: 2
POPS:
  - "AFR"
  - "EUR"
  
# Array SNP filtering
DATA_DIR: "data"

# HAPGEN setting
HAPGEN_NUM_HAPLOS: 200_000
HAPGEN2_PATH: "/u/project/pasaniuc/pasaniucdata/software/hapgen/hapgen2"

# admixture simulation software
ADMIX_SIMU_DIR: "/u/project/pasaniuc/pasaniucdata/admixture/software/admix-simu"
